### ISSUE TITLE
Requirements are missing a comma

### ISSUE THREAD

**Issue by eliramk** [MacHu-GWU/sqlalchemy_mate-project#3]
https://github.com/MacHu-GWU/sqlalchemy_mate-project/blob/e9f7cf7434c984f391758b9b915dad1e1cc774f9/requirements.txt#L1

Python Poetry seems to complain about this when installing packages. (Version 1.2.2)

Should be:
`sqlalchemy>=1.4.1,<2.0.0`

`Resolving dependencies... (589.3s)Invalid constraint (sqlalchemy (>=1.4.1<2.0.0)) found in sqlalchemy-mate-1.4.28.3 dependencies, skipping`

**Comment by jfalkenstein** [comment]
I'm running into this too! Can this be fixed?

**Comment by MacHu-GWU** [comment]
oh no, `sqlalchemy` they now made 2.X public available? I will do a quick fix soon folks.

**Comment by MacHu-GWU** [comment]
Hi folks, it is fixed in 1.4.48.4

**Comment by jfalkenstein** [comment]
Now _that's_ a great turnaround time! Thanks for fixing this so quickly!
